### ISSUE TITLE
how to seek time smooth 

### ISSUE THREAD

**Issue by TrungVu37** [NoonPacific/NPAudioStream#3]

**Comment by yetdog** [comment]
I too am interested in getting a working seek slider!

**Comment by gligorkot** [comment]
@TrungVu37 @yetdog Just use a `UISlider`

```
@IBAction func sliderValueChanged(_ sender: UISlider) {
        let progress = sender.value
        npAudioStream.seekToTime(inSeconds: CGFloat(progress))
}
```

all done.

**Comment by AlexGivens** [comment]
Solution provided by @gligorkot, closing issue.

**Comment by yetdog** [comment]
Isn't it much more than that, though? I have my slider, and it kicks off that function, sure. But it doesn't seek. It just drops me back to the beginning of the track.

Do I need to first calculate the length of the track and then set a min/max, and then calculate the new seek position and update the place on the mp3 track when moving the slider? Or is that already baked in somewhat?

**Comment by gligorkot** [comment]
Hey @yetdog, depends on if you're streaming or not? I was trying to do seeking on a stream and it didn't quite work, then I figured out it was because the stream I was using wasn't a "ranged" stream; it was just sending the file in one big block.

You can have a look at this answer on StackOverflow for more info [https://stackoverflow.com/a/20121557/717927](url)

I ended up downloading the file, then using NPAudioStream to just play a local file. And seek works in this case as the file is local so it knows about the length of the file etc.

This problem existed with all streaming libs I tried, and I tried a lot of them :)
